# Generated by Django 4.2.9 on 2024-02-08 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MaxLengthValidator(10, message='Phone number must be 10 characters long.'), django.core.validators.MinLengthValidator(10, message='Phone number must be 10 characters long.'), django.core.validators.RegexValidator(message='Phone number must contain only numeric number.', regex='^[7-9][0-9]{9}$')]),
        ),
    ]
