stages:
  - lint
  - test

variables:
  APP_NAME: "djangoapp"

before_script:
  - echo "Setting up environment"
  # - pip install -r requirements.txt  # Install your project's dependencies

lint:
  stage: lint
  script:
    - python3.9 src/manage.py runserver_with_lint  # Adjust the path to your source code
  only:
    - merge_requests
    - main

unit_test:
  stage: test
  script:
    - python src/manage.py test djangoapp.unit_tests
  only:
    - merge_requests
    - main

integration_test:
  stage: test
  script:
    - python src/manage.py test djangoapp.integration_tests
  only:
    - merge_requests
    - main
